### PR TITLE
Feature/media type handling for resources (do not merge)

### PR DESCRIPTION
**Pull request by bwehrle**
This is the first pass a resolving the issue [Issue 26](https://github.com/vlingo/vlingo-http/issues/26).
* Allows the selection of a mapper based on the content type via ContentTypeMapper
* Based on the accepted content types from the client, and the mappers registered, the response is serialized accordingly, using a new ObjectResponse Resouce handler.
* Its missing the small implementation pieces for the other request handler classes.  I wanted any feedback first.
* See comment below on the missing functional approach to the error handling.  I'm working on this now.

Looking forward to the feedback for any improvements; the final PR would clear up commits into single squashed commit.  

I believe this is related to solving [Issue 35](https://github.com/vlingo/vlingo-http/issues/35) as well.  It may require additional pieces related to encoding, but the content handling should be relevant.

### CODE REVIEW

**Comment by bwehrle** [comment]
Hi Vaughn,

Glad to hear that.  The things that are missing are:
* Replace the recoveryFrom with the stateful context solution we discussed.
* Copy/paste code & tests for the different ResourceHandler1-N.
I think I should have this done today, or be asking for help on point 1 if
I can't get the proposed solution to work.

I'd like to have a more general discussion about the lack of mocks in the
vlingo-http code.  The integration-testing approach and the repetitive
nature of the ResourceHandlerN classes has lead, from what I see, to
repeated test and very broad tests.  My thinking is that this would be a
good place to start using more mocks.  However, I don't see these used much
in the vlingo codebase, so I wanted to talk with you all about it.

Regards,
Brian

**Comment by VaughnVernon** [comment]
@bwehrle Thanks for your work on this. Given review is this ready to merge?

**Comment by bwehrle** [comment]
Hi,
The work is done, if it looks good I'll squash and make a new PR for
merging, since I made a lot of small commits.  In the end I had to remove
the Completes<Response> return type of the error handler.  The day we need
this we can look at how to do this better.  For now its not a problem at
all.
Regards,
Brian

**Comment by VaughnVernon** [comment]
@bwehrle Awesome! Squash away!

**Comment by bwehrle** [comment]
I created #37 with the changes squashed into a single commit.  It should all be good to go!

**Pull request closed without merging**
